name: Codex Apply → Auto PR

on:
  # optional: run manually from the Actions tab
  workflow_dispatch:
  # main trigger: when an Issue gets label "codex-apply"
  issues:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' &&
       github.event.action == 'labeled' &&
       github.event.label.name == 'codex-apply')
    runs-on: ubuntu-latest

    steps:
      - name: Debug payload
        run: |
          echo "EVENT: ${{ github.event_name }}"
          echo "ACTION: ${{ github.event.action }}"
          echo "LABEL: ${{ github.event.label.name }}"
          echo "--- raw ---"
          cat "$GITHUB_EVENT_PATH"

      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set bot identity
        run: |
          git config --global user.name "Huntsman AI Bot"
          git config --global user.email "bot@huntsmanoptics.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0 ruff==0.6.2 GitPython==3.1.43

      - name: Run edit script
        env:
          # Only needed if you later enable LLM edits
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AI_ALLOW_LIST: "src,app,configs,docs,.github"
          AI_MAX_CHANGED_LINES: "800"
        run: |
          if [ ! -f scripts/ai_edit_repo.py ]; then
            echo "Missing scripts/ai_edit_repo.py — commit it to default branch."
            exit 1
          fi
          python scripts/ai_edit_repo.py

      - name: Create / update PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ai/auto-updates
          title: "AI: automated code updates"
          commit-message: "AI: apply automated edits"
          body: |
            Automated changes generated by the Codex label-trigger workflow.
            Trigger: ${{ github.event_name }} • Actor: ${{ github.actor }}
          delete-branch: true
